CREATE TABLE a
(
    id INTEGER PRIMARY KEY,
    name CHAR (20)
);

CREATE TABLE b
(
    id  INTEGER PRIMARY KEY,
    age SMALLINT
);

INSERT INTO a VALUES (1, 'Alice');
INSERT INTO a VALUES (2, 'Bob');
INSERT INTO a VALUES (3, 'Carol');

INSERT INTO b VALUES (1, 25);
INSERT INTO b VALUES (2, 30);
INSERT INTO b VALUES (4, 22);

